### ISSUE TITLE
Add Travis CI unit test configuration

### ISSUE THREAD

**Issue by bendyer** [UAVCAN/libuavcan#64]
May need to skip timing-dependent tests if build VM is not sufficiently performant.

**Comment by pavel-kirienko** [comment]
It also makes sense to configure Travis to run Coverity Scan too.

See https://scan.coverity.com/travis_ci.

Instructions for manual build submission are here: https://github.com/UAVCAN/libuavcan#submitting-a-coverity-scan-build

**Comment by bendyer** [comment]
Just looped back to this—please could you visit https://travis-ci.org/profile/UAVCAN and enable those three repos?

**Comment by pavel-kirienko** [comment]
Done.

**Comment by bendyer** [comment]
@pavel-kirienko re: Coverity Scan, I have sent you an access request which will hopefully allow me to download the sample Travis CI configuration referenced in step 8 of https://scan.coverity.com/travis_ci

**Comment by pavel-kirienko** [comment]
Access granted.

**Comment by bendyer** [comment]
No luck. Please could you try to access it and send me the file? Instructions are:

> 6. From the Coverity Scan Dashboard, click `Project Settings`. Then, on the right, click the `Submit build` button.
> 7. Assuming the project is properly registered via GitHub, you'll see a tab for `Configure Travis CI`. Visit that panel.
> 8. On the Travis CI Configuration page, you'll see a sample `.travis-yml` file. It will have auto-generated several of the necessary project-specific fields, including the encrypted Coverity Scan token (necessary to upload results).

**Comment by pavel-kirienko** [comment]
OK, there's a problem with Coverity Scan indeed, I just emailed their tech support (you're CCed).

**Comment by pavel-kirienko** [comment]
Coverity's benevolent tech support helped us to resolve the problem. Here's the file, @bendyer:

```yaml
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "nCQtEBd5gQ9zirHNQVpzB0Q8aVKmMuTrlHfZCK5ZOpFItD9zP0YwqUTcw6y8T+14CceY6Go/D+fgeMYR3QmYc2CW0vXMwgBYOFQuPYEef7455ZPdt6wdr4lnyP/B+fj4cWZ4WhV+hMigl2Ly4xaFH6msm+PlIHOdjdaXo3ko0LI="

addons:
  coverity_scan:
    project:
      name: "UAVCAN/libuavcan"
      description: "UAVCAN in C++"
    notification_email: pavel.kirienko@gmail.com
    build_command_prepend: "rm -rf build &> /dev/null || true; mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Debug"
    build_command:   "make --ignore-errors"
    branch_pattern: coverity_scan
```
